version: 2

defaults:
    working_directory: ~/repo

jobs:
  build:
    # Run tests inside a docker container set up on CircleCI
    docker:
      - image: circleci/node:11.6.0

    # Steps to run tests
    steps:
      # Checkout the code
      - checkout

      - run:
          name: Setup the test reporter
          command: |
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: Install the node modules
          command: npm install

      # Save node_modules to cache to speed up subsequent builds
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules

      # run tests!
      - run: # run tests
          name: Run the tests and report coverage
          command: |
            ./cc-test-reporter before-build
            npm test
            ./cc-test-reporter after-build --exit-code $?
